on: [push]

jobs:
  install_ansible_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: jakubkotkowiak/ansible-test-action@main
        with:
          version: 2.9.3
